package remoteObject;


/**
* remoteObject/EnrollmentInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from EnrollmentInterface.idl
* Thursday, October 25, 2018 9:54:41 PM EDT
*/

public interface EnrollmentInterfaceOperations 
{

  /* Advisor Operations */
  boolean addCourse (String advisorId, String courseId, String semester, int capacity);
  boolean removeCourse (String advisorId, String courseId, String semester);
  org.omg.CORBA.Any listCourseAvailability (String advisorId, String semester);

  /* Student Operations */
  org.omg.CORBA.Any enrolCourse (String studentId, String courseId, String semester);
  org.omg.CORBA.Any getClassSchedule (String studentId);
  org.omg.CORBA.Any dropCourse (String studentId, String courseId);
  org.omg.CORBA.Any swapCourse (String studentId, String newCourseId, String oldCourseId);
} // interface EnrollmentInterfaceOperations
