package remoteObject;


/**
* remoteObject/EnrollmentInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from EnrollmentInterface.idl
* Thursday, October 25, 2018 9:54:41 PM EDT
*/

public interface EnrollmentInterface extends EnrollmentInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface EnrollmentInterface
