package remoteObject;

/**
* remoteObject/EnrollmentInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from EnrollmentInterface.idl
* Thursday, October 25, 2018 9:54:41 PM EDT
*/

public final class EnrollmentInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public remoteObject.EnrollmentInterface value = null;

  public EnrollmentInterfaceHolder ()
  {
  }

  public EnrollmentInterfaceHolder (remoteObject.EnrollmentInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = remoteObject.EnrollmentInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    remoteObject.EnrollmentInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return remoteObject.EnrollmentInterfaceHelper.type ();
  }

}
